### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by nesl247** [dracula/zsh#1]
Hey everyone,

We're looking for a maintainer for ZSH. Dracula theme has grown significantly and it's too much for one person. If you are interested in becoming the maintainer, please reply here.

We're not going to let issues and pull requests get behind though just because we don't have a dedicated maintainer, so fear not.

Thanks.
- Dracula Theme Team

**Comment by AGitBoy** [comment]
I would be interested in maintaining this. I have some experience in making prompts (I made one for local use once, before I found the agkozak theme, and later, this theme), and I am currently using the dracula theme (my config repo needs to be updated, so it won't be on there until I update my configs).

**Comment by Glennmen** [comment]
I could review PR's if that will help speedup the progress to get them merged. Not sure if I am any help in making changes myself, don't have any experience in ZSH custom theme development.

I use iTerm2 with Dracula theme + ZSH with Dracula theme.

**Comment by hacknug** [comment]
@AGitBoy as mentioned in the other issue, I've invited you to join the org so you can help maintaining this.

@Glennmen hey there! Do you think you could still help reviewing them? Maybe @AGitBoy would like an extra brain reviewing his PR (probably others too). Thanks either way!

**Comment by Glennmen** [comment]
@hacknug Sure! I am a big fan of dracula and would like to help out where I can.

**Comment by AGitBoy** [comment]
@Glennmen Help is always welcome! Reviewing PRs is a big help.

**Comment by dainmiller** [comment]
I love this theme @nesl247 and use it all the time - any PRs that come through I'll help out by reviewing them.
