### ISSUE TITLE
No space between arrow and current directory

### ISSUE THREAD

**Issue by jaminthorns** [dracula/zsh#13]
There is no space between the prompt arrow and the current directory:

![image](https://user-images.githubusercontent.com/6618434/64911792-ee965900-d6eb-11e9-9278-b3073112df97.png)

There is a space in the screenshot in the README, though: ![image](https://draculatheme.com/assets/img/screenshots/zsh.png)

Is this intentional or a visual regression? If intentional, I feel like the screenshot should be updated.

**Comment by AGitBoy** [comment]
This is not intentional, and it's very odd, as I am not able to replicate it. Could you post your `~/.zshrc` and the output of `zsh --version`?

**Comment by AGitBoy** [comment]
I must've deleted the space after the character accidentally, I'll push a fix soon.
