### ISSUE TITLE
Support vi mode

### ISSUE THREAD

**Issue by dielianhuachusai** [dracula/zsh#24]
I like vim and use vi mode.
I change my shell to zsh and install dracula theme. I cannot find any sign or color when I change to vi mode, Could you support vi mode ?

**Comment by AGitBoy** [comment]
Thanks for the suggestion!

Commit 569cad7b33596f24527cb312de3b9ffbffe8d6ff adds support for vi mode, by making the status arrow turn yellow when in command mode.
