### ISSUE TITLE
Creating a symlink between the theme and the omz theme directory doesn't make it show up in the omz theme list

### ISSUE THREAD

**Issue by Pistrie** [dracula/zsh#25]
I'm using this command to make a symlink:
`sudo ln -s ~/.local/themes/dracula/zsh/dracula.zsh-theme /usr/share/oh-my-zsh/custom/themes/dracula.zsh-theme`

exa shows the following as the symlink:
`dracula.zsh-theme -> /home/sylvester/.local/themes/dracula/zsh/dracula.zsh-theme`

when I search for the dracula theme in omz theme list I don't see the theme, only the default example.zsh-theme:
`omz theme list`
output:
`Custom themes:
example`

Am I doing something wrong?

**Comment by Maverick1872** [comment]
I don't believe you're doing anything wrong. I believe it's likely an issue with OMZ itself not being able to follow symlinks, as it's not listing any of my personal custom themes either. I'll be creating an issue over at OMZ for this personally.

**Comment by AGitBoy** [comment]
It's unfortunate that OMZ doesn't support following symlinks, personally I use [zplug](https://github.com/zplug/zplug) over OMZ as it's much better for managing plugins from a variety of sources.

I'm closing this as an upstream issue.
