### ISSUE TITLE
Issue in showing arrow in Tmux

### ISSUE THREAD

**Issue by kirpalricky** [dracula/zsh#30]
In tmux instead of an arrow, an underscore is shown.

<img width="82" alt="Screenshot 2021-06-03 at 6 54 35 PM" src="https://user-images.githubusercontent.com/6193130/120652243-356a4a80-c49d-11eb-9ce0-34fb6bdef895.png">

**Comment by AGitBoy** [comment]
This is most likely an issue with the way your terminal emulator and tmux display fonts and symbols, unicode character display (especially with tmux on) can be quite finnicky in many terminal emulators. In addition you might not have a font with the unicode symbol on your computer.

As a temporary fix, you can override the arrow icon in your zshrc, two possible soulutions that I've found in the past are adding a space character after the arrow character, which some terminals need to display larger unicode characters, like so:
```shell
DRACULA_ARROW_ICON='➜ '
```
If this doesn't work you can try setting the arrow icon to a more generic unicode character, like so
```shell
DRACULA_ARROW_ICON='→'
```

If neither of these work, please post what terminal you're using, the fonts you are using, your `.zshrc`, and your `.tmux.conf`

**Comment by kirpalricky** [comment]
Additional Information:

Terminal is default OSX Terminal (Catalina 10.15.7)
Font being used is Monaco

The arrow is working fine without tmux. So putting my tmux.conf contents below.

`# START-CLEANUP #
# Unbind the default tmux command prefix, CTRL+b.
unbind C-b

# Unbind keys for vertical & Horizontal split
unbind '"'
unbind %
# END-CLEANUP #

# START-PREFERENCE #
# Set zsh as default shell
set-option -g default-shell /bin/zsh

# Use ` as our tmux command prefix.
set -g prefix `
bind a set -g prefix C-a
bind ` set -g prefix ` 

# Lower the default tmux delay, this makes tmux more responsive.
set -s escape-time 1

# start session number from 1 rather than 0
set -g base-index 1

# start pane number from 1 similar to windows
set -g pane-base-index 1

# don't rename windows automatically
set-option -g allow-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# vertical split
bind | split-window -h

# horizontal split
bind - split-window -v

# Screen like kill bindings
bind-key k confirm-before -p "kill-window #W? (y/n)" kill-window 

# Make tmux use 256 colors.
set -g default-terminal "screen-256color"

# Make tmux act like xterm to prevent Vim issues:
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Store a lot of history.
set -g history-limit 100000

# enable mouse
set -g mouse on

# Allow copying using mouse and vi like yank
set-option -s set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
#bind-key -T copy-mode-vi y send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'

# Customise Status line
set-option -g status on                # turn the status bar on
set -g status-interval 5               # set update frequencey (default 15 seconds)

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Customise what appears on status line
set -g status-left " "
set -g status-right "[#(uptime | sed 's/.*load averages: //')] #[fg=black]%d %b (%a) %l:%M %p "
set -g status-right-length 75

# END-PREFERENCE #
`

**Comment by kirpalricky** [comment]
Hi solved the issue by following solution proposed on [this issue](https://github.com/tmux/tmux/issues/1602)

Basically needed to start tmux with -u pramaeter.
