### ISSUE TITLE
the arrow showing whether correct

### ISSUE THREAD

**Issue by PerseusFu** [dracula/zsh#31]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
<img width="124" alt="图片" src="https://user-images.githubusercontent.com/85473693/120961423-63e37080-c790-11eb-9ab6-de9d00677422.png">
Sorry but as the pic above, there should be an arrow showing whether the code is right. However, In my iTerm2 +Ohmyzsh showing the pic below.
<img width="209" alt="图片" src="https://user-images.githubusercontent.com/85473693/120961575-a86f0c00-c790-11eb-980d-69704d1f45fb.png">
 
If there is anything wrong when installing ?
 THX

**Comment by AGitBoy** [comment]
Are you referring to the check mark shown in the first screenshot? That doesn't show whether the code is right, it's the git status indicator. If it is a check mark (✔), it means that the git status is clean, if it is a x (✗) it means that the git status is dirty. The marks only show when you are in a git repository and have git installed.

**Comment by PerseusFu** [comment]
Many Thx
