### ISSUE TITLE
arrow display error and gitstatus disappear

### ISSUE THREAD

**Issue by cloud-mist** [dracula/zsh#38]
# Problem
I use st terminal, oh-my-zsh and dracula theme for a long time.
Recently I find my gitstatus icon disappear. I dont know what happened. 

And today I uninstall oh-my-zsh and install zplug and reinstall dracula.
After that, the arrow icon display weird.

What should I do,Please help me.
Thanks.

# Img
Now the Dir is a git repository.

![image](https://user-images.githubusercontent.com/49445212/147101051-64bcc4f3-5a17-41df-8d11-0c8b8b69c51e.png)

# zshrc
```
export TERM_ITALICS=true

# ========== Proxy ============
#export https_proxy=http://127.0.0.1:8889
#export http_proxy=http://127.0.0.1:8889


# ============ Alias ===========
alias ra='lf-ueberzug'
alias vim='nvim'
alias s='neofetch'
alias sudo='sudo -E'
alias lg='lazygit'
alias zc="vim ~/.zshrc"

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias top='bpytop'

alias cat='bat'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"


# ============ Go =============
export GOPATH=$HOME/study/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin
export GOPROXY=https://goproxy.io,direct

# =========== Gem =============
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"

export PATH="$PATH:$HOME/.local/bin"


# Hint color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#845050,bg=bold"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# other thing
source ~/zsh/emoji-cli/emoji-cli.zsh
source ~/.config/lf/lf_icons.sh
source ~/zsh/fzf.zsh


# ---------------
#	   zplug
# ---------------
source /usr/share/zsh/scripts/zplug/init.zsh

zplug "davidde/git"
zplug "zdharma-continuum/fast-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "dracula/zsh", as:theme


if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load
```

**Comment by avalonwilliams** [comment]
Can you tell me what font you're using? This is a problem that sometimes happens in st depending on the font. A solution I've used in the past is to change the arrow icon to a different unicode arrow than the one used in the theme:
```sh
DRACULA_ARROW_ICON='→'
```

Oh and make sure you update the repository, I recall having the git prompt being broken on an older version, if this doesn't work please let me know, thank you!

**Comment by cloud-mist** [comment]
Thanks a lot for your reply.

> Can you tell me what font you're using?

Sauce Code Pro Nerd Font / Fira Code Nerd Font.

The solution(Change ICON)  works.

> make sure you update the repository, I recall having the git prompt being broken on an older version

Now I use `Fish` shell , and the dracula theme works very well. About this solution , I dont know  the result .
