### ISSUE TITLE
Add support for posh-git

### ISSUE THREAD

**Issue by vanmash** [dracula/zsh#41]
Please consider adding support for posh-git. I would love to have detailed `git` information shown on the right integrated into the main prompt.

![posh-git2](https://user-images.githubusercontent.com/2527832/150573604-7690c814-408c-46ac-b456-0c6eea118203.png)

references:
https://github.com/lyze/posh-git-sh
https://dahlbyk.github.io/posh-git/

**Comment by avalonwilliams** [comment]
I added the ability to disable the git segment so you can replace it with the posh thing, add this to the config after the posh files have been loaded. 

```shell
DRACULA_DISPLAY_GIT=0
PROMPT="${PROMPT:0:-1}$(__posh_git_echo) "
```

**Comment by vanmash** [comment]
Hi @avalonwilliams 

thank you for that!

PS: I've noticed that version is the same
`# Dracula Theme v1.2.5`
