### ISSUE TITLE
Some colors and fonts are not exactly as the demo picture

### ISSUE THREAD

**Issue by liubq7** [dracula/zsh#42]
Hi there, I installed Dracula for zsh manually, but it looks not exactly like the picture you privided:
<img width="908" alt="截屏2022-03-06 15 56 17" src="https://user-images.githubusercontent.com/55693386/156914501-d5772a97-ff58-4d8d-a8ad-c010685d5c0c.png">

What I did:
* Move dracula.zsh-theme file to oh-my-zsh's theme folder: oh-my-zsh/themes/dracula.zsh-theme.
* Move /lib to oh-my-zsh's theme folder: oh-my-zsh/themes/lib.
* Go to ~/.zshrc file and set ZSH_THEME="dracula"

Is there anything I missed?

**Comment by avalonwilliams** [comment]
Hi, this is not really an issue with the theme, this is more of an issue with your terminal setup. The original screencap is of (I'm fairly certain), MacOS's default terminal with the "Linux colors" color scheme, and (I'm not 100% sure on this) either the [Menlo font](https://en.wikipedia.org/wiki/Menlo_(typeface)) or the [SF Mono Font](https://developer.apple.com/fonts/).

I don't know what terminal emulator you're using, so I can't provide configs but this chart shows the color values that Terminal.app uses
![image](https://user-images.githubusercontent.com/30708886/157131093-0f8941cc-da9d-4673-b7da-f4a09b36d671.png)

**Comment by cj-obrien** [comment]
> Hi there, I installed Dracula for zsh manually, but it looks not exactly like the picture you privided: 

@liubq7 I believe the "missing" syntax highlighting you were asking about is provided by the [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) plugin.
