### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by Dzejk0p** [dracula/zsh#45]
On a few devices after updating to the newest version there is a problem with autocomplete. When typing command and tabbing new command copies instead of replace actual line.
<img width="585" alt="Screen Shot 2022-06-09 at 11 58 54" src="https://user-images.githubusercontent.com/74422920/172821121-1a0f468c-fadb-48a6-b262-52ee1d381a39.png">
.

**Comment by Dzejk0p** [comment]
Maybe it is worth mentioning that it started to do it on the newest commit only

**Comment by yungParrot** [comment]
@Dzejk0p look at this comment :point_right:  https://github.com/dracula/zsh/issues/46#issuecomment-1164654524 :cowboy_hat_face:

**Comment by avalonwilliams** [comment]
Should be fixed by #48. Sorry about not getting to this sooner, I've been extremely busy with prepping to move to Boston.
