### ISSUE TITLE
When the tab key is pressed for automatic completion, the previous character is repeated

### ISSUE THREAD

**Issue by lemontree2000** [dracula/zsh#46]
https://user-images.githubusercontent.com/21957062/173190844-5bf9ff59-688a-47fd-9695-74a3865eb160.mov

**Comment by lucasvs** [comment]
This commit 350fdfeb4cf687af231150a639849dd4221d3c9a causes the issue. reverting to d7626ad9ed3fb1929082bd3d6815160d8e016247 works fine.

**Comment by lemontree2000** [comment]
@yungParrot @lucasvs thx , I finally solved this problem by commenting this code 😂
<img width="674" alt="image" src="https://user-images.githubusercontent.com/21957062/177142997-fa010c36-a75d-405b-b289-ab3252b4bd0d.png">

**Comment by kbtombul** [comment]
I don't know enough about zsh to dig deeper but here's a Unix & Linux Stack Exchange question & answer that seemed relevant: https://unix.stackexchange.com/a/85066

For the time being, I'm sticking with d7626ad as well.

cc @avalonwilliams (I'm sure you're getting the issue emails already, I'm just hoping this helps get to the solution.)

**Comment by JannoTjarks** [comment]
As far I understood it is a problem with the syntax of the zsh built-in function. I already tried to fix the problem, but it only works without the colors for me. 
The syntax of the colors adds a wrong spacing to the current line.

**Comment by avalonwilliams** [comment]
This should be fixed by #48, thanks to JannoTjarks, sorry for not being able to fix this sooner, I've been prepping to move to Boston so I've been very busy the past month or so.
