### ISSUE TITLE
display error, after apply dracula theme

### ISSUE THREAD

**Issue by Pengfei73** [dracula/zsh#47]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/91525851/173553248-961d4d2b-f589-4474-9920-236e3d652628.png">
- using iterm2 + oh my zsh
- after apply dracula theme, auto suggestion seem displayed at wrong place and can not delete

**Comment by Pengfei73** [comment]
And also for centos7 zsh when apply dracula theme on master
![image](https://user-images.githubusercontent.com/91525851/174513162-975c3a09-fe40-4a1f-b926-83196d2f20e5.png)

**Comment by yungParrot** [comment]
@Pengfei73 look at this comment :point_right:  https://github.com/dracula/zsh/issues/46#issuecomment-1164654524 :cowboy_hat_face:

**Comment by archervanderwaal** [comment]
> @Pengfei73 look at this comment 👉 [#46 (comment)](https://github.com/dracula/zsh/issues/46#issuecomment-1164654524) 🤠

It doesn't work.

**Comment by kimnagui** [comment]
Works fine when reset to 6e256a1c143331ae20d4fa81625fd647990dd9d9

**Comment by avalonwilliams** [comment]
Fixed by #48, sorry for not getting to this sooner, I've been busy prepping to move to Boston the past month.

**Comment by MakerFace** [comment]
Will this be fixed in a future release?

**Comment by JannoTjarks** [comment]
@MakerFace this should be fixed by #48
