### ISSUE TITLE
zplug support

### ISSUE THREAD

**Issue by smit9612** [dracula/zsh#7]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by pxgamer** [comment]
It works with zplug, just use:
```sh
zplug 'dracula/zsh', as:theme
```

**Comment by zenorocha** [comment]
@pxgamer thanks for answering @smit9612! What do you think of adding that information on https://draculatheme.com/zsh? You can send a PR on https://github.com/dracula/dracula.github.io/blob/site/src/content/zsh/index.html ;)

**Comment by pxgamer** [comment]
Sure 👍

**Comment by zenorocha** [comment]
We're also looking for a maintainer to this theme, so if you're interested I can put on the organization ;)

**Comment by pxgamer** [comment]
Added a PR (dracula/dracula.github.io#54).

Unfortunately I just use this theme, so I probably wouldn't be confident in maintaining the project.

**Comment by zenorocha** [comment]
No problem at all, thanks @pxgamer!
